---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: content
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/The Rite of Marriage
  label: The rite of marriage
  create: all
  match: "**/*"
- type: directory
  path: content/Home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/The Wedding Mass
  label: The wedding mass
  create: all
  match: "**/*"
- type: directory
  path: content/Other Resources
  label: Other resources
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.64.1
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.64.1
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.64.1
